name: Upload Assets to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ASSETS_UPLOAD_ROLE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ASSETS_UPLOAD_ROLE_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync assets to S3
        run: |
          aws s3 sync ./assets s3://${{ secrets.S3_BUCKET_ASSETS }}/ --delete
